# Generated by Django 3.1.5 on 2021-01-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Nvidia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='speedBottom',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='speedTop',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gpu',
        ),
        migrations.AddField(
            model_name='cpu',
            name='speed',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpu',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ram',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ram',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Gpu',
        ),
        migrations.AddField(
            model_name='game',
            name='amd',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.amd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='nvidia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.nvidia'),
            preserve_default=False,
        ),
    ]
