# Generated by Django 3.1.5 on 2021-01-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210113_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='release',
            field=models.CharField(max_length=20),
        ),
    ]
